/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Console: typeof import('./src/components/Console.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    Editor: typeof import('./src/components/editor/Editor.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    IftaLabel: typeof import('primevue/iftalabel')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MdiAlert: typeof import('~icons/mdi/alert')['default']
    MdiAlertOctagon: typeof import('~icons/mdi/alert-octagon')['default']
    MdiChevronDoubleLeft: typeof import('~icons/mdi/chevron-double-left')['default']
    MdiChevronDoubleRight: typeof import('~icons/mdi/chevron-double-right')['default']
    MdiChevronLeft: typeof import('~icons/mdi/chevron-left')['default']
    MdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    MdiClose: typeof import('~icons/mdi/close')['default']
    MdiCodeTags: typeof import('~icons/mdi/code-tags')['default']
    MdiCog: typeof import('~icons/mdi/cog')['default']
    MdiConsole: typeof import('~icons/mdi/console')['default']
    MdiContentSave: typeof import('~icons/mdi/content-save')['default']
    MdiContentSaveEdit: typeof import('~icons/mdi/content-save-edit')['default']
    MdiDebugStepInto: typeof import('~icons/mdi/debug-step-into')['default']
    MdiDebugStepOut: typeof import('~icons/mdi/debug-step-out')['default']
    MdiDebugStepOver: typeof import('~icons/mdi/debug-step-over')['default']
    MdiDelete: typeof import('~icons/mdi/delete')['default']
    MdiFolderOpen: typeof import('~icons/mdi/folder-open')['default']
    MdiHome: typeof import('~icons/mdi/home')['default']
    MdiLinkVariant: typeof import('~icons/mdi/link-variant')['default']
    MdiMemory: typeof import('~icons/mdi/memory')['default']
    MdiPause: typeof import('~icons/mdi/pause')['default']
    MdiPlay: typeof import('~icons/mdi/play')['default']
    MdiPower: typeof import('~icons/mdi/power')['default']
    MdiRefresh: typeof import('~icons/mdi/refresh')['default']
    MdiShuffle: typeof import('~icons/mdi/shuffle')['default']
    MdiTimer: typeof import('~icons/mdi/timer')['default']
    MdiWrench: typeof import('~icons/mdi/wrench')['default']
    Menubar: typeof import('primevue/menubar')['default']
    NavIcon: typeof import('./src/components/nav-menu/NavIcon.vue')['default']
    NavMenu: typeof import('./src/components/nav-menu/NavMenu.vue')['default']
    OverlayBadge: typeof import('primevue/overlaybadge')['default']
    Popover: typeof import('primevue/popover')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Simulator: typeof import('./src/components/simulator/Simulator.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
