/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Console: typeof import('./src/components/Console.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    Editor: typeof import('./src/components/editor/Editor.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    MdiAlert: typeof import('~icons/mdi/alert')['default']
    MdiCodeTags: typeof import('~icons/mdi/code-tags')['default']
    MdiCog: typeof import('~icons/mdi/cog')['default']
    MdiMemory: typeof import('~icons/mdi/memory')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Popover: typeof import('primevue/popover')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Simulator: typeof import('./src/components/simulator/Simulator.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    Tabs: typeof import('primevue/tabs')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
